# Generated by Django 3.2.7 on 2021-09-09 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='pricing',
            field=models.CharField(default=1, max_length=10, verbose_name='Pricing'),
            preserve_default=False,
        ),
    ]
